### ISSUE TITLE
Have you taken a look at appium?

### ISSUE THREAD

**Issue by Jonahss** [joemasilotti/ios-feature-testing#3]
Full wrapper over Intruments uiautomation, with a lot of workarounds and bugfixes automatically included.
Basically it is "Selenium for Mobile". Uses the same api.

**Comment by joemasilotti** [comment]
Appium sounds cool but I've never used it first hand. I am happy to accept PRs from those more experienced in the framework.

**Comment by Jonahss** [comment]
Oh cool. I'll hook you up.

Plus appium is currently looking into automating using XCUITest, so we hope to get the benefits of that as well.

My PR will be pretty biased ;)

**Comment by Jonahss** [comment]
What are focus tests?

**Comment by Jonahss** [comment]
Here we go: https://github.com/joemasilotti/ios-feature-testing/pull/4
Easier to view on my fork: https://github.com/Jonahss/ios-feature-testing

**Comment by joemasilotti** [comment]
Thanks for the help! I've commented on the PR (#4) so I'm going to close this issue.
